name: Hexo Github Deploy
on:
  push:
    branches:
      - master
jobs:
    markdown-link-check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - uses: gaurav-nelson/github-action-markdown-link-check@v1
          # with:
          #   use-quiet-mode: 'yes'
          #   use-verbose-mode: 'yes'
          #   check-modified-files-only: 'yes'
    build:
      if: github.triggering_actor != 'whitecodes'
      runs-on: ubuntu-latest
      steps:
        - name: Checkout source
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: latest
            check-latest: true
        - name: Setup hexo
          run: |
            npm install hexo-cli -g
            npm install
        - name: hexo build
          run: |
            npm run clean
            npm run build
    deploy:
      if: github.triggering_actor == 'whitecodes'
      runs-on: ubuntu-latest
      needs: markdown-link-check
      steps:
        - name: Checkout source
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: latest
            check-latest: true
        - name: Setup hexo
          env:
            ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
          run: |
            mkdir -p ~/.ssh/
            echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "whitemailg@gmail.com"
            git config --global user.name "white"
            npm install hexo-cli -g
            npm install
        - name: Hexo deploy
          run: |
            npm run deploy
