name: Hexo Github Actions
on: [push]
jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout source
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: latest
            check-latest: true
            # cache: 'npm'
            # cache-dependency-path: ./package-lock.json
        # - name: Cache NPM dependencies
        #   uses: actions/cache@v3
        #   with:
        #     path: ~/.npm
        #     key: ${{ runner.OS }}-npm-cache
        #     restore-keys: |
        #       ${{ runner.OS }}-npm-cache
        - name: Setup hexo
          env:
            ACTION_DEPLOY_KEY: ${{ secrets.HEXO_DEPLOY_PRI }}
          run: |
            mkdir -p ~/.ssh/
            echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            if [ ! -f "$file" ]; then
              echo "$ACTION_DEPLOY_KEY" > home/runner/.ssh/id_rsa
              chmod 600 home/runner/.ssh/id_rsa
            fi
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            git config --global user.email "whitemailg@gmail.com"
            git config --global user.name "white"
            npm install hexo-cli -g
            npm install
        - name: Hexo deploy
          run: |
            npm run deploy
